title: Anh Le Tech Blog
name: Anh Le
description: System Engineer | Cloud | Kubernetes | Ceph

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: dark

search: true

powered_by: false

author:
  name: Anh Le
  avatar: "/assets/images/avatar.png"
  bio: "System Engineer | Cloud Infrastructure"
  location: Vietnam
  email: anhlx2502@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anhlx2502"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"

    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@anhlx2502"
      
markdown: kramdown
highlighter: rouge

atom_feed:
  hide: true
footer:
  links: []

include:
  - _pages