title: Anh Le Tech Blog
name: Anh Le
description: System Engineer | Cloud | Kubernetes | Ceph

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

author:
  name: Anh Le
  bio: System Engineer | Cloud Infrastructure
  location: Vietnam
  email: anhlx2502@gmail.com

minimal_mistakes_skin: dark
search: true

markdown: kramdown
highlighter: rouge

include:
  - _pages